name: Build

on:
  push:
    branches: [ "main", "add_actions_packaging" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create OpenWRT package
        uses: OpenTollGate/tollgate-sdk@to-reusable-action
        with:
          packageName: 'tollgate-module-relay-go'
          makeFilePath: 'Makefile'
